<a href="https://colab.research.google.com/github/Athira-codes/ml-projects/blob/main/practice(carresale).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [117]:
import pandas as pd
df=pd.read_csv('/content/drive/MyDrive/DATASETS/train-data.csv')
df

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
0,0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6 km/kg,998 CC,58.16 bhp,5.0,NaN,1.75
1,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,NaN,12.50
2,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.2 kmpl,1199 CC,88.7 bhp,5.0,8.61 Lakh,4.50
3,3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,NaN,6.00
4,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2 kmpl,1968 CC,140.8 bhp,5.0,NaN,17.74
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6014,6014,Maruti Swift VDI,Delhi,2014,27365,Diesel,Manual,First,28.4 kmpl,1248 CC,74 bhp,5.0,7.88 Lakh,4.75
6015,6015,Hyundai Xcent 1.1 CRDi S,Jaipur,2015,100000,Diesel,Manual,First,24.4 kmpl,1120 CC,71 bhp,5.0,NaN,4.00
6016,6016,Mahindra Xylo D4 BSIV,Jaipur,2012,55000,Diesel,Manual,Second,14.0 kmpl,2498 CC,112 bhp,8.0,NaN,2.90
6017,6017,Maruti Wagon R VXI,Kolkata,2013,46000,Petrol,Manual,First,18.9 kmpl,998 CC,67.1 bhp,5.0,NaN,2.65
6018,6018,Chevrolet Beat Diesel,Hyderabad,2011,47000,Diesel,Manual,First,25.44 kmpl,936 CC,57.6 bhp,5.0,NaN,2.50

In [118]:
df.isna().sum()

Unnamed: 0              0
Name                    0
Location                0
Year                    0
Kilometers_Driven       0
Fuel_Type               0
Transmission            0
Owner_Type              0
Mileage                 2
Engine                 36
Power                  36
Seats                  42
New_Price            5195
Price                   0
dtype: int64

In [119]:
df.drop(['Unnamed: 0','New_Price'],axis=1,inplace=True)
df

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Price
0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6 km/kg,998 CC,58.16 bhp,5.0,1.75
1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,12.50
2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.2 kmpl,1199 CC,88.7 bhp,5.0,4.50
3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,6.00
4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2 kmpl,1968 CC,140.8 bhp,5.0,17.74
...,...,...,...,...,...,...,...,...,...,...,...,...
6014,Maruti Swift VDI,Delhi,2014,27365,Diesel,Manual,First,28.4 kmpl,1248 CC,74 bhp,5.0,4.75
6015,Hyundai Xcent 1.1 CRDi S,Jaipur,2015,100000,Diesel,Manual,First,24.4 kmpl,1120 CC,71 bhp,5.0,4.00
6016,Mahindra Xylo D4 BSIV,Jaipur,2012,55000,Diesel,Manual,Second,14.0 kmpl,2498 CC,112 bhp,8.0,2.90
6017,Maruti Wagon R VXI,Kolkata,2013,46000,Petrol,Manual,First,18.9 kmpl,998 CC,67.1 bhp,5.0,2.65
6018,Chevrolet Beat Diesel,Hyderabad,2011,47000,Diesel,Manual,First,25.44 kmpl,936 CC,57.6 bhp,5.0,2.50

In [120]:
df.dtypes

Name                  object
Location              object
Year                   int64
Kilometers_Driven      int64
Fuel_Type             object
Transmission          object
Owner_Type            object
Mileage               object
Engine                object
Power                 object
Seats                float64
Price                float64
dtype: object

In [121]:
df['Mileage']=df['Mileage'].str.replace('kmpl','')
df['Mileage']=df['Mileage'].str.replace('km/kg','')
df['Engine']=df['Engine'].str.replace('CC','')
df['Power']=df['Power'].str.replace('bhp','')
df['Power']=df['Power'].str.replace('null','0')
df

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Price
0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6,998,58.16,5.0,1.75
1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67,1582,126.2,5.0,12.50
2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.2,1199,88.7,5.0,4.50
3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77,1248,88.76,7.0,6.00
4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2,1968,140.8,5.0,17.74
...,...,...,...,...,...,...,...,...,...,...,...,...
6014,Maruti Swift VDI,Delhi,2014,27365,Diesel,Manual,First,28.4,1248,74,5.0,4.75
6015,Hyundai Xcent 1.1 CRDi S,Jaipur,2015,100000,Diesel,Manual,First,24.4,1120,71,5.0,4.00
6016,Mahindra Xylo D4 BSIV,Jaipur,2012,55000,Diesel,Manual,Second,14.0,2498,112,8.0,2.90
6017,Maruti Wagon R VXI,Kolkata,2013,46000,Petrol,Manual,First,18.9,998,67.1,5.0,2.65
6018,Chevrolet Beat Diesel,Hyderabad,2011,47000,Diesel,Manual,First,25.44,936,57.6,5.0,2.50

In [122]:
df.loc[df['Power']=='null '][['Power']]

Empty DataFrame
Columns: [Power]
Index: []

In [123]:
df['Mileage']=df['Mileage'].astype(float)
df['Engine']=df['Engine'].astype(float)
df['Power']=df['Power'].astype(float)

In [124]:
df.isna().sum()

Name                  0
Location              0
Year                  0
Kilometers_Driven     0
Fuel_Type             0
Transmission          0
Owner_Type            0
Mileage               2
Engine               36
Power                36
Seats                42
Price                 0
dtype: int64

In [125]:
import numpy as np

In [126]:
df.loc[df.Power==0,'Power']=np.NaN

In [127]:
lst1=['Engine','Seats']
for i in lst1:
  df[i]=df[i].fillna(df[i].mode()[0])
lst2=['Mileage','Power']
for i in lst2:
  df[i]=df[i].fillna(df[i].mean())

In [128]:
df

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Price
0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.60,998.0,58.16,5.0,1.75
1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67,1582.0,126.20,5.0,12.50
2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.20,1199.0,88.70,5.0,4.50
3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77,1248.0,88.76,7.0,6.00
4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.20,1968.0,140.80,5.0,17.74
...,...,...,...,...,...,...,...,...,...,...,...,...
6014,Maruti Swift VDI,Delhi,2014,27365,Diesel,Manual,First,28.40,1248.0,74.00,5.0,4.75
6015,Hyundai Xcent 1.1 CRDi S,Jaipur,2015,100000,Diesel,Manual,First,24.40,1120.0,71.00,5.0,4.00
6016,Mahindra Xylo D4 BSIV,Jaipur,2012,55000,Diesel,Manual,Second,14.00,2498.0,112.00,8.0,2.90
6017,Maruti Wagon R VXI,Kolkata,2013,46000,Petrol,Manual,First,18.90,998.0,67.10,5.0,2.65
6018,Chevrolet Beat Diesel,Hyderabad,2011,47000,Diesel,Manual,First,25.44,936.0,57.60,5.0,2.50

In [129]:
df['brand']=df['Name'].apply(lambda x:x.split()[0])
df

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Price,brand
0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.60,998.0,58.16,5.0,1.75,Maruti
1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67,1582.0,126.20,5.0,12.50,Hyundai
2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.20,1199.0,88.70,5.0,4.50,Honda
3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77,1248.0,88.76,7.0,6.00,Maruti
4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.20,1968.0,140.80,5.0,17.74,Audi
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6014,Maruti Swift VDI,Delhi,2014,27365,Diesel,Manual,First,28.40,1248.0,74.00,5.0,4.75,Maruti
6015,Hyundai Xcent 1.1 CRDi S,Jaipur,2015,100000,Diesel,Manual,First,24.40,1120.0,71.00,5.0,4.00,Hyundai
6016,Mahindra Xylo D4 BSIV,Jaipur,2012,55000,Diesel,Manual,Second,14.00,2498.0,112.00,8.0,2.90,Mahindra
6017,Maruti Wagon R VXI,Kolkata,2013,46000,Petrol,Manual,First,18.90,998.0,67.10,5.0,2.65,Maruti
6018,Chevrolet Beat Diesel,Hyderabad,2011,47000,Diesel,Manual,First,25.44,936.0,57.60,5.0,2.50,Chevrolet

In [130]:
df.drop(['Name'],axis=1,inplace=True)
df

,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Price,brand
0,Mumbai,2010,72000,CNG,Manual,First,26.60,998.0,58.16,5.0,1.75,Maruti
1,Pune,2015,41000,Diesel,Manual,First,19.67,1582.0,126.20,5.0,12.50,Hyundai
2,Chennai,2011,46000,Petrol,Manual,First,18.20,1199.0,88.70,5.0,4.50,Honda
3,Chennai,2012,87000,Diesel,Manual,First,20.77,1248.0,88.76,7.0,6.00,Maruti
4,Coimbatore,2013,40670,Diesel,Automatic,Second,15.20,1968.0,140.80,5.0,17.74,Audi
...,...,...,...,...,...,...,...,...,...,...,...,...
6014,Delhi,2014,27365,Diesel,Manual,First,28.40,1248.0,74.00,5.0,4.75,Maruti
6015,Jaipur,2015,100000,Diesel,Manual,First,24.40,1120.0,71.00,5.0,4.00,Hyundai
6016,Jaipur,2012,55000,Diesel,Manual,Second,14.00,2498.0,112.00,8.0,2.90,Mahindra
6017,Kolkata,2013,46000,Petrol,Manual,First,18.90,998.0,67.10,5.0,2.65,Maruti
6018,Hyderabad,2011,47000,Diesel,Manual,First,25.44,936.0,57.60,5.0,2.50,Chevrolet

In [133]:
# labelencoder
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['Owner_Type']=le.fit_transform(df['Owner_Type'])
le1=LabelEncoder()
df['brand']=le1.fit_transform(df['brand'])
le2=LabelEncoder()
df['Transmission']=le2.fit_transform(df['Transmission'])
le3=LabelEncoder()
df['Fuel_Type']=le3.fit_transform(df['Fuel_Type'])
le4=LabelEncoder()
df['Location']=le4.fit_transform(df['Location'])
df
df

,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Price,brand
0,9,2010,72000,0,1,0,415,998.0,58.16,5.0,1.75,18
1,10,2015,41000,1,1,0,292,1582.0,126.20,5.0,12.50,10
2,2,2011,46000,4,1,0,250,1199.0,88.70,5.0,4.50,9
3,2,2012,87000,1,1,0,324,1248.0,88.76,7.0,6.00,18
4,3,2013,40670,1,0,2,155,1968.0,140.80,5.0,17.74,1
...,...,...,...,...,...,...,...,...,...,...,...,...
6014,4,2014,27365,1,1,0,425,1248.0,74.00,5.0,4.75,18
6015,6,2015,100000,1,1,0,390,1120.0,71.00,5.0,4.00,10
6016,6,2012,55000,1,1,2,113,2498.0,112.00,8.0,2.90,17
6017,8,2013,46000,4,1,0,271,998.0,67.10,5.0,2.65,18
6018,5,2011,47000,1,1,0,403,936.0,57.60,5.0,2.50,4

In [135]:
mapping=list(zip(le.classes_,le.transform(le.classes_)))
mapping

[(0, 0), (1, 1), (2, 2), (3, 3)]

In [137]:
mapping=list(zip(le1.classes_,le1.transform(le1.classes_)))
mapping

[('Ambassador', 0),
 ('Audi', 1),
 ('BMW', 2),
 ('Bentley', 3),
 ('Chevrolet', 4),
 ('Datsun', 5),
 ('Fiat', 6),
 ('Force', 7),
 ('Ford', 8),
 ('Honda', 9),
 ('Hyundai', 10),
 ('ISUZU', 11),
 ('Isuzu', 12),
 ('Jaguar', 13),
 ('Jeep', 14),
 ('Lamborghini', 15),
 ('Land', 16),
 ('Mahindra', 17),
 ('Maruti', 18),
 ('Mercedes-Benz', 19),
 ('Mini', 20),
 ('Mitsubishi', 21),
 ('Nissan', 22),
 ('Porsche', 23),
 ('Renault', 24),
 ('Skoda', 25),
 ('Smart', 26),
 ('Tata', 27),
 ('Toyota', 28),
 ('Volkswagen', 29),
 ('Volvo', 30)]

In [138]:
mapping=list(zip(le2.classes_,le2.transform(le2.classes_)))
mapping

[('Automatic', 0), ('Manual', 1)]

In [139]:
mapping=list(zip(le3.classes_,le3.transform(le3.classes_)))
mapping

[('CNG', 0), ('Diesel', 1), ('Electric', 2), ('LPG', 3), ('Petrol', 4)]

In [140]:
mapping=list(zip(le4.classes_,le4.transform(le4.classes_)))
mapping

[('Ahmedabad', 0),
 ('Bangalore', 1),
 ('Chennai', 2),
 ('Coimbatore', 3),
 ('Delhi', 4),
 ('Hyderabad', 5),
 ('Jaipur', 6),
 ('Kochi', 7),
 ('Kolkata', 8),
 ('Mumbai', 9),
 ('Pune', 10)]

In [134]:
df.dtypes

Location               int64
Year                   int64
Kilometers_Driven      int64
Fuel_Type              int64
Transmission           int64
Owner_Type             int64
Mileage                int64
Engine               float64
Power                float64
Seats                float64
Price                float64
brand                  int64
dtype: object

In [141]:
X=df.drop(['Price'],axis=1)
X

,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,brand
0,9,2010,72000,0,1,0,415,998.0,58.16,5.0,18
1,10,2015,41000,1,1,0,292,1582.0,126.20,5.0,10
2,2,2011,46000,4,1,0,250,1199.0,88.70,5.0,9
3,2,2012,87000,1,1,0,324,1248.0,88.76,7.0,18
4,3,2013,40670,1,0,2,155,1968.0,140.80,5.0,1
...,...,...,...,...,...,...,...,...,...,...,...
6014,4,2014,27365,1,1,0,425,1248.0,74.00,5.0,18
6015,6,2015,100000,1,1,0,390,1120.0,71.00,5.0,10
6016,6,2012,55000,1,1,2,113,2498.0,112.00,8.0,17
6017,8,2013,46000,4,1,0,271,998.0,67.10,5.0,18
6018,5,2011,47000,1,1,0,403,936.0,57.60,5.0,4

In [143]:
y=df.iloc[:,-2]
y

0        1.75
1       12.50
2        4.50
3        6.00
4       17.74
        ...
6014     4.75
6015     4.00
6016     2.90
6017     2.65
6018     2.50
Name: Price, Length: 6019, dtype: float64

In [144]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=1)

In [145]:
X_train.shape,y_train.shape

((4213, 11), (4213,))

In [146]:
X_test.shape,y_test.shape

((1806, 11), (1806,))

In [147]:
from sklearn.linear_model import LinearRegression
mlr=LinearRegression()
mlr.fit(X_train,y_train)

LinearRegression()

In [148]:
y_pred=mlr.predict(X_test)
y_pred

array([38.45393733,  2.27995613, 11.41485339, ...,  2.46318169,
        3.75427899,  2.44548313])

In [149]:
y_test

2319    78.80
3652     3.51
2397     6.00
3536    10.28
4400     2.35
        ...
4865     5.77
3194    24.77
1253     2.00
1041     4.57
1697     3.25
Name: Price, Length: 1806, dtype: float64

In [150]:
import numpy as np

In [151]:
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error
print("r2_score=",r2_score(y_test,y_pred))
print("MAE=",mean_absolute_error(y_test,y_pred))
print("MSE=",mean_squared_error(y_test,y_pred))
print("RMSE=",np.sqrt(mean_squared_error(y_test,y_pred)))

r2_score= 0.5873185104496468
MAE= 3.6405651444815725
MSE= 49.007698918165794
RMSE= 7.000549901126753

In [154]:
import warnings
warnings.filterwarnings('ignore')

In [155]:
y_new=mlr.predict([[9,2010,72000,0,1,0,26.60,998.0,58.16,5.0,18]])
y_new.item()

1.1773425526750998